### ISSUE TITLE
Textmate 2 Bundle conflict with PHP

### ISSUE THREAD

**Issue by xipasduarte** [Anomareh/PHP-Twig.tmbundle#49]
The PHP-twig bundle is making the PHP bundle not style the *.php files.
PHP Bundle https://github.com/textmate/php.tmbundle

**Comment by Anomareh** [comment]
This bundle doesn't interact with PHP files [in any way][scopes]. PHP is only in the name as Twig is a PHP library. My best guess would be a configuration issue or a modification to your local copy of the bundle.

[scopes]: https://github.com/Anomareh/PHP-Twig.tmbundle/blob/master/Syntaxes/HTML%20(Twig).tmLanguage#L7-L8
