### ISSUE TITLE
Doesn't work with Sublime Text2

### ISSUE THREAD

**Issue by fanyang-ceg** [Anomareh/PHP-Twig.tmbundle#50]
I copied all files into the PHP-Twig folder, restarted sublime text editor (version 2.0.2, Build 2221), still now syntax highlight.

**Comment by Anomareh** [comment]
This is most likely a theme issue, most themes don't support the bundle. You can try one of my [TextMate themes][tm-themes] or edit your current theme to your liking, the scopes are listed in the [README][scopes]. If it's not a problem with your theme, please reopen this issue so we can figure out what might be going wrong.

[scopes]: https://github.com/Anomareh/PHP-Twig.tmbundle#scopes
[tm-themes]: https://github.com/Anomareh/TextMate-Themes
