### ISSUE TITLE
HTML comments are always printed as Twig comments

### ISSUE THREAD

**Issue by djmtype** [Anomareh/PHP-Twig.tmbundle#67]
I installed this plugin. Now when using the default keyboard shortcut (super+alt+forward_slash) to toggle a comment, the output always returns as `{# … #}` instead of `<!-- … -->` regardless of if the file type is HTML, PHP or TWIG.

So, I removed this package, and the HTML comments still output as `{# … #}`.

How do I get back my HTML (`<!-- … -->`) comments back?

**Comment by uhnomoli** [comment]
Sounds like the snippets weren't properly removed. What editor are you using?

**Comment by djmtype** [comment]
Using Sublime Text 3. The keyboard shortcut is the default in ST3. Even if I choose toggle comment from the menu I still get a Twig comment format, not HTML – and that's after this package has been uninstalled.

**Comment by djmtype** [comment]
@Anomareh I've been troubleshooting this issue further. It seems Nunjucks Extended package is causing the conflict, not this package. It didn't clean itself up after I removed it, and kept a nunjucks-extended directory inside my User directory. I threw it away, and all is normal. Apologies!

**Comment by uhnomoli** [comment]
No worries, glad you got it worked out.
